import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Eye, EyeOff, Loader2, MapPin, PackagePlus, Plus, Trash2 } from "lucide-react";
import { supabase } from "../lib/supabaseClient";
import { useAuth } from "../context/AuthContext";

export default function MyListings() {
  const { user } = useAuth();
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [workingId, setWorkingId] = useState("");
  const load = useCallback(async () => { if (!user) return; setLoading(true); setError(""); const { data, error: fetchError } = await supabase.from("items").select("*, categories(name, icon), item_images(url, sort_order)").eq("owner_id", user.id).order("created_at", { ascending: false }); if (fetchError) setError(fetchError.message); setItems(data || []); setLoading(false); }, [user]);
  useEffect(() => { load(); }, [load]);
  async function toggleAvailability(item) { setWorkingId(item.id); setError(""); const { error: updateError } = await supabase.from("items").update({ is_available: !item.is_available }).eq("id", item.id); if (updateError) setError(updateError.message); await load(); setWorkingId(""); }
  async function deleteItem(item) { if (!window.confirm(`Delete “${item.title}”? This will remove its listing and related bookings.`)) return; setWorkingId(item.id); setError(""); const { error: deleteError } = await supabase.from("items").delete().eq("id", item.id); if (deleteError) setError(deleteError.message); await load(); setWorkingId(""); }
  return <section className="market-page"><div className="market-wrap"><div className="page-heading"><div><p className="section-kicker">Host dashboard</p><h1>My listings</h1><p>Control availability and manage every item you share.</p></div><Link to="/add-item" className="btn-primary"><Plus size={18} /> List an item</Link></div>{error && <p className="form-alert" role="alert">{error}</p>}{loading ? <div className="loading-state"><Loader2 className="animate-spin" /> Loading your listings…</div> : items.length === 0 ? <div className="empty-market"><PackagePlus size={34} /><h2>Your shelf is empty</h2><p>Add your first item and it will appear here for you to manage.</p><Link to="/add-item" className="btn-primary"><Plus size={18} /> List an item</Link></div> : <div className="listing-manager-grid">{items.map((item) => { const image = [...(item.item_images || [])].sort((a, b) => a.sort_order - b.sort_order)[0]?.url; const working = workingId === item.id; return <article className="listing-manager-card" key={item.id}><Link to={`/item/${item.id}`} className="listing-manager-image">{image ? <img src={image} alt={item.title} /> : <span>📦</span>}<span className={`availability-pill ${item.is_available ? "available" : "hidden"}`}>{item.is_available ? "Available" : "Hidden"}</span></Link><div className="listing-manager-body"><div><p className="listing-category">{item.categories?.icon || "📦"} {item.categories?.name || "Uncategorised"}</p><Link to={`/item/${item.id}`}><h2>{item.title}</h2></Link><p className="listing-meta"><MapPin size={14} /> {item.location || "Pickup location not set"}</p></div><div className="listing-manager-footer"><strong>₹{Number(item.price_per_day).toLocaleString("en-IN")} <small>/ day</small></strong><div className="listing-actions"><button disabled={working} onClick={() => toggleAvailability(item)}>{working ? <Loader2 className="animate-spin" size={16} /> : item.is_available ? <EyeOff size={16} /> : <Eye size={16} />}{item.is_available ? "Hide" : "Show"}</button><button disabled={working} className="danger" onClick={() => deleteItem(item)}><Trash2 size={16} /> Delete</button></div></div></div></article>; })}</div>}</div></section>;
}
